"use client";

import { useState } from "react";
import { Bell, CalendarDays, Camera, CarFront, Check, ChevronRight, ClipboardCheck, ClipboardList, Clock3, Ellipsis, Phone, Plus, ScanLine, Search, Settings2, Sparkles, StickyNote, UserRound, Wrench, X } from "lucide-react";
import { buildDashboardSummary, filterJobRows, formatMileage, formatRelative, initials, matchesCustomerQuery, matchesVehicleQuery, vehicleTitle } from "../lib/data/vehicle-record.mjs";
import type { CreationMode } from "./creation-flows";
import type { Customer, Job, Vehicle } from "../lib/data/schema.d.mts";
import type { VehicleListRow } from "../lib/data/vehicle-record.d.mts";
import { el } from "./i18n";

const APP_VERSION = "2.1.11";
const APP_RELEASE = "Phase 1";

type View = "home" | "cars" | "work" | "customers" | "settings";

export function Dashboard({ t, lang, session, greeting, todayLabel, summary, startScanner, selectView, notice }: { t: typeof el; lang: "el" | "en"; session: string; greeting: string; todayLabel: string; summary: ReturnType<typeof buildDashboardSummary> | null; startScanner: () => void; selectView: (view: View) => void; notice: (message: string) => void }) {
  return <><section className="intro-row"><div><p className="eyebrow">{todayLabel}</p><h1>{greeting}</h1><p className="intro-copy">{t.subtitle}</p></div><button className="notification" onClick={() => notice(t.notificationsEmpty)} aria-label={t.notificationsTitle}><Bell size={18}/><i/></button></section>
    <section className="scan-card"><div className="scan-orb"><ScanLine size={30}/></div><div className="scan-copy"><span className="pill"><Sparkles size={13}/> AI READY</span><h2>{t.scanTitle}</h2><p>{t.scanText}</p></div><button className="scan-button" onClick={startScanner}>{t.scan}<span><Camera size={16}/></span></button></section>
    <section className="metrics"><button onClick={() => selectView("work")}><div className="metric-row"><span className="metric-icon indigo"><CalendarDays size={16}/></span><strong>{summary?.openCount ?? "—"}</strong></div><p>{t.activeJobs}</p></button><button onClick={() => notice(t.note)}><div className="metric-row"><span className="metric-icon aqua"><StickyNote size={16}/></span><strong>{summary?.noteCount ?? "—"}</strong></div><p>{t.notes}</p></button><button onClick={() => selectView("work")}><div className="metric-row"><span className="metric-icon gold"><ClipboardCheck size={16}/></span><strong>{summary?.openCount ?? "—"}</strong></div><p>{t.jobs}</p></button></section>
    <section className="section-heading"><div><p className="eyebrow">{t.activity}</p><h2>{t.garage}</h2></div><button onClick={() => selectView("work")}>{t.all}<ChevronRight size={15}/></button></section>
    <section className="activity-list">{(summary?.recent ?? []).map(({ job, vehicle }, index) => <button className="activity" key={job.id} onClick={() => selectView("work")}><span className={"activity-icon " + (index === 0 ? "lilac" : index === 1 ? "blue" : "mint")}>{job.status === "in_progress" ? <Wrench size={18}/> : job.status === "done" ? <Check size={18}/> : <Clock3 size={18}/>}</span><span className="activity-text"><strong>{vehicle ? ([vehicle.make, vehicle.model].filter(Boolean).join(" ") || vehicle.plate) : job.title}</strong><small>{vehicle ? vehicle.plate + " · " : ""}{formatRelative(job.updated_at ?? job.created_at)}</small></span><Ellipsis size={18}/></button>)}</section>
  </>;
}

export function Intro({ eyebrow, title, action }: { eyebrow: string; title: string; action?: React.ReactNode }) { return <section className="page-intro"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1></div>{action}</section>; }
export function SearchBox({ value, setValue, placeholder }: { value: string; setValue: (value: string) => void; placeholder: string }) { return <label className="search-field"><Search size={18}/><input value={value} onChange={(event) => setValue(event.target.value)} placeholder={placeholder}/>{value && <button aria-label="Clear search" onClick={() => setValue("")}><X size={16}/></button>}</label>; }
export function Empty({ text }: { text: string }) { return <div className="empty-inline"><Search size={20}/>{text}</div>; }

export function Cars({ t, lang, query, setQuery, rows, selectVehicle, vehiclePhotos }: { t: typeof el; lang: "el" | "en"; query: string; setQuery: (value: string) => void; rows: VehicleListRow[]; selectVehicle: (vehicleId: string) => void; vehiclePhotos: Map<string, string|null> }) {
  const filtered = rows.filter((row) => matchesVehicleQuery(row, query));
  const tones = ["mint", "blue", "peach", "lilac"];
  return <><Intro eyebrow={t.allCars} title={t.cars} action={<span className="page-count">{rows.length}</span>}/><SearchBox value={query} setValue={setQuery} placeholder={t.searchCar}/><section className="vehicle-list">{filtered.map((row, index) => <button className="vehicle-row" key={row.vehicle.id} onClick={() => selectVehicle(row.vehicle.id)}>{vehiclePhotos.get(row.vehicle.id) ? <img src={vehiclePhotos.get(row.vehicle.id)!} alt={row.vehicle.plate} className="vehicle-thumb"/> : <span className={"vehicle-badge " + tones[index % tones.length]}><CarFront size={19}/></span>}<span className="vehicle-text"><strong>{row.vehicle.plate || t.unknownVehicle}<small>{[row.title, row.subtitle].filter(Boolean).join(" · ")}</small></strong><small>{[row.customer?.name ?? t.noCustomer, row.vehicle.mileage_km !== null ? formatMileage(row.vehicle.mileage_km, lang) : null].filter(Boolean).join(" · ")}</small><em>{row.currentJob?.title ?? t.noOpenJob}</em></span><ChevronRight size={18}/></button>)}{!filtered.length && <Empty text={rows.length ? t.noResults : t.noVehicles}/>}</section></>;
}

export function Work({ t, lang, jobRows, selectVehicle, notice, openCreation, onJobUpdate, vehiclePhotos }: { t: typeof el; lang: "el" | "en"; jobRows: Array<{ job: Job; vehicle: Vehicle | null; customer: Customer | null }>; selectVehicle: (id: string) => void; notice: (message: string) => void; openCreation: (mode: CreationMode) => void; onJobUpdate: (jobId: string, status: string) => void; vehiclePhotos: Map<string, string|null> }) {
  function nextStatus(s: string) { return s === "scheduled" ? "in_progress" : s === "in_progress" ? "done" : "scheduled"; }
  function nextLabel(s: string) { return s === "scheduled" ? t.markInProgress : s === "in_progress" ? t.markDone : t.reopen; }
  const [scope, setScope] = useState<"today" | "active" | "history">("today");
  const visibleJobs = filterJobRows(jobRows, scope);
  return <><Intro eyebrow={t.activeJobs} title={t.work} action={<button className="compact-add" onClick={() => openCreation("job")}><Plus size={16}/>{t.add}</button>}/><div className="filter-tabs"><button className={scope === "today" ? "active" : ""} onClick={() => setScope("today")}>{t.todayFilter}</button><button className={scope === "active" ? "active" : ""} onClick={() => setScope("active")}>{t.progress}</button><button className={scope === "history" ? "active" : ""} onClick={() => setScope("history")}>{t.history}</button></div><section className="job-list">{visibleJobs.map(({ job, vehicle, customer }) => { const statusClass = job.status === "in_progress" ? "active" : job.status; return <article className="job-card" key={job.id}><div className="job-top">{vehiclePhotos.get(vehicle?.id ?? "") ? <img src={vehiclePhotos.get(vehicle?.id ?? "")!} alt={vehicle?.plate ?? ""} className="vehicle-thumb"/> : <span className={"vehicle-badge " + (["mint","blue","peach","lilac"][Math.abs(job.id.charCodeAt(4) ?? 0) % 4])}><CarFront size={15}/></span>}<div className="job-top-text"><strong className="job-plate">{vehicle?.plate ?? t.unknownVehicle}</strong><small>{[vehicleTitle(vehicle), customer?.name].filter(Boolean).join(" · ") || t.noCustomer}</small></div></div><p>{job.title}</p><footer><span className={"job-status-label " + statusClass}>{statusClass === "active" ? t.markInProgress : statusClass === "done" ? t.statusDone : statusClass === "cancelled" ? t.statusCancelled : t.statusScheduled}</span><button className="job-status-btn" onClick={() => onJobUpdate(job.id, nextStatus(job.status))}>{nextLabel(job.status)}</button><button className="job-open-btn" onClick={() => vehicle && selectVehicle(vehicle.id)}>{t.open}<ChevronRight size={14}/></button></footer></article>; })}{!visibleJobs.length && <Empty text={scope === "history" ? t.noHistory : t.noOpenJob}/>}</section></>;
}

export function Customers({ t, query, setQuery, customerRows, selectVehicle, notice, openCreation }: { t: typeof el; query: string; setQuery: (value: string) => void; customerRows: Array<{ customer: any; vehicles: any[]; vehicleCount: number }>; selectVehicle: (id: string) => void; notice: (message: string) => void; openCreation: (mode: CreationMode) => void }) {
  const TONES = ["mint", "blue", "peach", "lilac"];
  const filtered = customerRows.filter((row) => matchesCustomerQuery(row, query));
  return <><Intro eyebrow={t.customerList} title={t.customers} action={<button className="compact-add" onClick={() => openCreation("customer")}><Plus size={16}/>{t.add}</button>}/><SearchBox value={query} setValue={setQuery} placeholder={t.searchCustomer}/><section className="customer-list">{filtered.map((row, idx) => <article className="customer-row" key={row.customer.id}><span className={"avatar " + TONES[idx % TONES.length]}>{initials(row.customer.name)}</span><div><strong>{row.customer.name}</strong>{row.customer.phone ? <a href={"tel:" + row.customer.phone.replaceAll(" ", "")}><Phone size={13}/>{row.customer.phone}</a> : <small>{t.noPhone}</small>}<small><CarFront size={13}/>{row.vehicles.length ? row.vehicles.map((v: any) => v.plate).join(", ") : t.noVehicles}</small></div><span className="car-count" onClick={() => row.vehicles[0] && selectVehicle(row.vehicles[0].id)} style={{cursor: row.vehicles.length ? "pointer" : "default"}}>{row.vehicleCount}<small>{t.vehicles}</small></span></article>)}{!filtered.length && <Empty text={customerRows.length ? t.noResults : t.noVehicles}/>}</section></>;
}

export function Settings({ t, theme, chooseTheme, lang, switchLanguage, userName, saveUserName, commitUserName }: { t: typeof el; theme: string; chooseTheme: (theme: string) => void; lang: string; switchLanguage: () => void; userName: string; saveUserName: (name: string) => void; commitUserName: (name: string) => void }) {
  return <><Intro eyebrow={t.preferences} title={t.settings}/><section className="settings-group"><p className="eyebrow">{t.appearance}</p><label className="setting-row name-setting"><span><span className="setting-icon"><UserRound size={17}/></span>{t.yourName}</span><input aria-label={t.yourName} value={userName} onChange={(event) => saveUserName(event.target.value)} onBlur={(event) => commitUserName(event.target.value)} placeholder={t.namePlaceholder}/></label><div className="setting-row"><span><span className="setting-icon"><Sparkles size={17}/></span>{t.theme}</span><div className="theme-select">{["sky", "pearl", "midnight"].map((item) => <button key={item} className={theme === item ? "selected" : ""} onClick={() => chooseTheme(item)}>{item}</button>)}</div></div><button className="setting-row" onClick={switchLanguage}><span><span className="setting-icon"><UserRound size={17}/></span>{t.language}</span><strong>{lang.toUpperCase()}<ChevronRight size={17}/></strong></button><p className="app-version">Motofy v{APP_VERSION} · {APP_RELEASE}</p></section></>;
}
